# 工作流名称
name: Build and Push Docker Image to GHCR

# 触发条件：在 push 到 main 分支时触发
on:
  push:
    branches: [ "main" ]

# 环境变量
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}

# 工作流中的任务
jobs:
  build-and-push:
    # 指定运行环境
    runs-on: ubuntu-latest
    # 授予权限
    permissions:
      contents: read
      packages: write

    # 任务执行步骤
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- 新增的步骤 ---
      # 设置 Docker Buildx，这是解决缓存问题的关键
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          # 现在 Buildx 已设置，下面这两行缓存配置可以正常工作了
          cache-from: type=gha
          cache-to: type=gha,mode=max
